# Docker compose version used
version: '3.8'
# Services or containers to be used
services:
  db-mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'polls'
    volumes:
      - ~/balanceadores/data:/var/lib/mysql
    networks:
      - balance-network

  balanceadores-1:       # name of the service/container
    image: rafaelrfq/balanceadores
    ports:
      - 8080:8080
    environment:    # environment variables
      - spring.datasource.url=jdbc:mysql://db-mysql:3306/polls
      - spring.datasource.username=root
      - spring.datasource.password=password
      - MYSQL_HOST=db-mysql
      - server.port=8080
    networks:    # network to connect containers
      - balance-network
    volumes:
      - balance-volume:/tmp/
    depends_on:   # indicates what to load first
      - db-mysql

networks:
  balance-network:

volumes:
  balance-volume: